import { Injectable } from '@angular/core';
import { PdfStyleService } from './pdf-style.service';
import jsPDF from 'jspdf';

@Injectable({ providedIn: 'root' })
export class PdfCoverService {
  constructor(private style: PdfStyleService) {}

  addCover(
    doc: jsPDF,
    config: any,
    pageWidth: number,
    pageHeight: number
  ): void {
    doc.setFillColor(255, 255, 255);
    doc.rect(0, 0, pageWidth, pageHeight, 'F');

    doc.addImage(this.style.coverLogo.url, 'PNG', 0, 0, 100, 50);

    doc.addImage(
      this.style.coverImages.topRight,
      'PNG',
      pageWidth - 60,
      0,
      60,
      80
    );

    const centerX = pageWidth / 2;
    let y = pageHeight / 2 - 30;

    // Report title
    doc.setFont(this.style.defaultStyling.font, 'bold');
    doc.setFontSize(20);
    doc.setTextColor(...this.style.defaultStyling.primaryColor);
    doc.text(
      config.coverPageConfig?.title || config.pdfTitle || 'Report',
      centerX,
      y,
      { align: 'center' }
    );

    y += 15;

    // Static From and To date (labels gray, dates black & bold, consistent spacing)
    const fromDate = '01-Jan-2025';
    const toDate = '31-Dec-2025';
    const labelFont = this.style.defaultStyling.font;
    const spacing = 3; // space between label and date

    // Draw "From:" label in gray
    doc.setFont(labelFont, 'normal');
    doc.setFontSize(12);
    doc.setTextColor(120, 120, 120);
    const fromLabelX = centerX - 35;
    doc.text('From:', fromLabelX, y, { align: 'left' });

    // Draw from date in black & bold right next to label
    const fromLabelWidth = doc.getTextWidth('From:') + spacing;
    doc.setFont(labelFont, 'bold');
    doc.setTextColor(0, 0, 0);
    doc.text(fromDate, fromLabelX + fromLabelWidth, y, { align: 'left' });

    // Draw "To:" label in gray
    const toLabelX =
      fromLabelX + fromLabelWidth + doc.getTextWidth(fromDate) + spacing * 2;
    doc.setFont(labelFont, 'normal');
    doc.setTextColor(120, 120, 120);
    doc.text('To:', toLabelX, y, { align: 'left' });

    // Draw to date in black & bold right next to label (same spacing)
    const toLabelWidth = doc.getTextWidth('To:') + spacing;
    doc.setFont(labelFont, 'bold');
    doc.setTextColor(0, 0, 0);
    doc.text(toDate, toLabelX + toLabelWidth, y, { align: 'left' });

    y += 15;

    // Custom line with "solutions" in green
    const line1 = 'Smart operating solutions for more productive facilities';
    const words = line1.split(' ');
    let offsetX = 0;

    words.forEach((word) => {
      if (word === 'solutions') {
        doc.setTextColor(0, 128, 0); // green
      } else {
        doc.setTextColor(0, 0, 0); // black
      }
      doc.text(word, centerX + offsetX - doc.getTextWidth(line1) / 2, y);
      offsetX += doc.getTextWidth(word + ' ');
    });

    y += 10;

    // Generated by line
    doc.setFont(this.style.defaultStyling.font, 'normal');
    doc.setFontSize(10);
    doc.setTextColor(0, 0, 0);
    doc.text('This report is generated by CleanTech company', centerX, y, {
      align: 'center',
    });

    y += 15;

    doc.addImage(
      this.style.coverImages.bottomRight,
      'PNG',
      pageWidth - 100,
      pageHeight - 120,
      100,
      120
    );
  }
}
